version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/android:2023.08
    working_directory: ~/project
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout

      - run:
          name: Set Gradle Wrapper Permissions
          command: chmod +x ./gradlew

      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "gradle.properties" }}
            - gradle-cache-

      - run:
          name: Run Unit Tests
          command: ./gradlew test

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-{{ checksum "gradle.properties" }}

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/reports

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
